#!/usr/bin/env python
""" Do report on current numpy state
"""
from __future__ import print_function

import os
import sys

from subprocess import check_call


def main():
    for ext in ('.so', '.pyd', '.dll'):
        fname = 'npsizes' + ext
        if os.path.isfile(fname):
            os.unlink(fname)
    check_call([sys.executable, 'setup.py', 'build_ext', '--inplace'])
    from npsizes import get_mem_size, get_def_sizes
    for name, def_sz in zip(('dtype', 'ndarray', 'ufunc'),
                            get_def_sizes()):
        print('{0}: static size {1}; memory size {2}'.format(
            name, def_sz, get_mem_size('numpy', name)))


if __name__ == '__main__':
    main()
