#!/usr/bin/env python
""" Do report on current numpy state

Run from npsizes project root directory (containing setup.py):

    ./npreport
"""
from __future__ import print_function

import os
from os.path import isfile
import sys

from subprocess import check_call


def nuke_exts():
    for ext in ('.so', '.pyd', '.dll'):
        fname = 'npsizes' + ext
        if os.path.isfile(fname):
            os.unlink(fname)


def main():
    if not isfile('npsizes.c'):
        raise RuntimeError("Run from npsizes root directory")
    nuke_exts()
    check_call([sys.executable, 'setup.py', 'build_ext', '--inplace'])
    from npsizes import get_mem_size, get_def_sizes
    for name, def_sz in zip(('dtype', 'ndarray', 'ufunc'),
                            get_def_sizes()):
        print('{0}: static size {1}; memory size {2}'.format(
            name, def_sz, get_mem_size('numpy', name)))


if __name__ == '__main__':
    main()
